import os, shutil, platform

env = Environment()
#env.Append( ENV = {'PATH' : os.environ['PATH'] })


if(platform.system() == "Linux"):
   
   env.Append( CPPFLAGS = '-g -Wall -pedantic -std=c++0x' )
   env.Append( LINKFLAGS = '-Wall ' )

   env.Append( LIBS = [ 'log4cxx' ] )

   env.Program('test', ['test.cpp', '../calc/settings.cpp', '../calc/status.cpp'])
